// <auto-generated />
namespace PracticeNewProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddedParkingLots : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedParkingLots));
        
        string IMigrationMetadata.Id
        {
            get { return "202005282012145_AddedParkingLots"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
